# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KA1EM's wiki
email: wangkaiminchn#gmail.com
description: Hi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ka1em.github.io" # the base hostname & protocol for your site
twitter_username: ka1em
github_username:  ka1em

# Build settings
markdown: kramdown
